### PR TITLE
Development

### LINKED ISSUE #4: Still need styles.css reload
Still need styles.css reload

_Originally posted by @codyduong in https://github.com/codyduong/hitokage/issues/3#issuecomment-2185422851_

### LINKED ISSUE #14: On bar removal restore MonitorWorkAreaOffset
https://github.com/codyduong/hitokage/blob/780b7beb23587a7ebbd8dfce552da0cfbd296b96/hitokage-core/src/widgets/bar.rs#L142-L145

If a bar is destroyed either on purpose or program crash, we will have a weird gap at where the bar once was.

So set MonitorWorkAreaOffset to 0,0,0,0

### PR DESCRIPTION
**Pull request by codyduong**
* Resolves #4 
* Resolves #14 
* Adds bar options, for full spec see: [bar.lua](https://github.com/codyduong/hitokage/blob/dev/hitokage-lua/src/widgets/bar.rs)
  * `width integer?`
  * `height integer?`
  * `offset BarOffset?`
* Adds workspace options, for full spec see: [workspace.lua](https://github.com/codyduong/hitokage/blob/dev/hitokage-lua/src/widgets/workspace.rs)
  * `item_width integer?`
  * `item_height integer?`
  * `halign Align?`

### CODE REVIEW

**Comment by codyduong** [comment]
Rename workspace options from width, height (since this could be the widgets overall width and height) to something like item-width, item-height

File: hitokage-lua/src/widgets/clock.rs [hunk 1]
```diff
@@ -25,23 +24,18 @@ impl UserData for ClockUserData {
...
-            _ => Ok(Value::Nil),
-          },
+      |lua, instance, key| -> Result<mlua::Value<'lua>, mlua::Error> {
+        match key.to_str().unwrap() {
+          "type" => Ok(lua.to_value(&instance.r#type.clone())?),
           _ => Ok(Value::Nil),
         }
       },
-    )
+    );
```
Comment (codyduong) [inline hitokage-lua/src/widgets/clock.rs:39]: Why support this syntax at all? No need to store `r#type` as a struct member.

This is for greater discussion on supporting syntactic sugar such as `type`, `format`

I have am having trouble with using `methods.add_meta_method("__newindex", ...` which is holding back most of the work on syntactic sugar. Either convert this to `get_type` or a method rather than a "field"

If we remove it be sure to remove `r#type` declarations here

https://github.com/codyduong/hitokage/blob/0679370e6e1cfc2296e7fb497e99a5023c3abd8d/hitokage-lua/src/widgets/mod.rs#L18-L42

Comment (codyduong) [reply hitokage-lua/src/widgets/clock.rs:39]: Moved to #16 for greater discussion

File: hitokage-core/src/widgets/workspace.rs [hunk 2]
```diff
@@ -187,30 +296,123 @@ fn update_workspaces(root: &gtk4::FlowBox, workspaces: &Vec<WorkspaceState>) ->
...
+            Some(&prev),
+            gtk4::ConstraintAttribute::End,
+            1.0,
+            0.0,
+            1001001000,
+          );
+
+          to_check_constraints.push(constraint);
+        }
+      }
```
Comment (codyduong) [inline hitokage-core/src/widgets/workspace.rs:370]: We need to change this constraint if we are at our `halign` was set to `End`, since then we expect to go backwards.

**Comment by codyduong** [comment]
There are some stability issues with the `FlowBox` constraint, namely the width is sometimes not set to the minimum of the children, causing alignment issues (and css issues if you use Flowbox for styling). It will eventually resolve correctly, but TODO investigate cause.

Most common on program startup or when new workspace child is made.

**Comment by codyduong** [comment]
Create an option on `Workspace` that accepts a callback to format workspace label based on index or workspace label (if there is one).

Should have a shape like so
```function format_label(index, name) ... end```
